# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 66fd52c
_src_path: gh:schwallergroup/copier-liac-minimal
author_email: diogo.santosmartins@epfl.ch
author_name: Diogo Santos Martins
github_org: dsantos03
package_name: chrfinder
project_name: Chrfinder
short_description: The package find the best chromatography based on properties of
    the mixture
